### ISSUE TITLE
Unsupported "high" direction

### ISSUE THREAD

**Issue by raboof** [EnotionZ/gpio#31] opened 2014-08-19 22:40 UTC
The sys API supports a "high" direction, which sets the direction to "out" but also sets the initial value to "1".

**Comment by EnotionZ** [comment] 2018-10-01 00:58
This will be resolved with #57, closing since it's a dupe of #38

**Closed by EnotionZ** 2018-10-01 00:58 UTC
Labels: duplicate

**Comment by juransaber** [comment] 2019-03-05 08:29
I also need this.
